### PR TITLE
Side selection

### LINKED ISSUE #34: canTransform exception in drive spamming warning log
By using `canTransform(...)` i was hoping for something like a **"wait for transform"** behavior. 

It did the trick, but while checking for the transform it spams a lot of warning messages like `Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist` in the log.

I haven't found anything that will simply prevent this warning from appearing. So in order to avoid [this garbage](https://github.com/robotique-ecam/cdfr/runs/1841765193#step:7:113) to appear, i decided to disable the log of drive node.

[As discussed with @3wnbr1 in #31](https://github.com/robotique-ecam/cdfr/pull/31#discussion_r583165664), this move is too rough, we need to work around to achieve a smoother solution and keep the log of drive.

@3wnbr1 comes with:
> See example below to catch exceptions
> https://github.com/ros2/geometry2/blob/ros2/tf2_ros/src/tf2_echo.cpp

### PR DESCRIPTION
**Pull request by PhileasL**
# Purpose of this PR

A way better and cleaner way to provide the side across the software. Also "fixes" (not really, just found another way) #34.

# What has been done ?

- Clean localisation node,
- Fix #34,
- Delete transformix package,
- Update transformix_msgs package, 
- Implement a new side selection transmission across the software.

## Clean localisation node

Removing VLX and it's dependencies as we're not going to use them with the new incoming lighthouse package.

## Update transformix_msgs package

The only service remaining in transformix_msgs is `InitialStaticTFsrv` containing:
- Request:
  - Bool: final_set
  - TransformStamped: map_odom_static_tf
- Response:
  - Bool: acquittal

## New side selection software architecture 

Alright now let's talk about this new way of transmitting the side across the software.

First of all, keep in mind that despite the fact each component of the system (assurancetourix, asterix, obelix) needs the side, they're 3 independent systems, so they can be started in whatever order. Same thing into asterix and obelix with the transmission of the static transformation between localisation and drive according to the side, localisation node can either start before or after drive node.

Here's the trick:
- Drive node:
  - At startup:
    - Loads a default transformation that is neither blue or yellow,
    - Creates a service `<namespace>/intial_tf_to_drive` (transformix_msgs/InitialStaticTFsrv type),
  - -> Callback on this service just updating its static transformation `_map_to_odom_tf` and sending back `acquittal=true`

- Localisation node:
  - At startup:
    - Create a service `<namespace>/initial_side_selection` (transformix_msgs/InitialStaticTFsrv type),
    - Create a client `<namespace>/intial_tf_to_drive`(transformix_msgs/InitialStaticTFsrv type),
    - By default, the side is blue, so localisation tries to send the blue side initial static transformation to drive using `<namespace>/intial_tf_to_drive`:
      - Create a timer that will tries every 2 seconds to send the transformation to drive (which isn't necessarily started),
        - If after two seconds, the service didn't get any answer, cancel the client request and retries
        - else If after two seconds the service answer but not `acquittal=true`, retries
        - else the message has reached his destination, deletion of the timer.
  - -> Callback on `<namespace>/initial_side_selection` service (transformix_msgs/InitialStaticTFsrv type) -> msg from assurancetourix containing the final side of the match:
    - map_odom_static_tf in the message is useless, **if final_set = true, the side is blue, else the side is yellow (final_set = false )** ( Yes, I was too lazy to implement another type of service),
    - If a transmission is trying to happen on `<namespace>/intial_tf_to_drive`, delete this one and the timer,
    - Update the initial static transformation to send to drive considering the final side,
    - Start a timer that follow the precedent layout,
    - Send back `acquittal=true` to assurancetourix.

- Assurancetourix node:
  - At startup, find the side by computer vision,
  - set up a transformix_msgs/InitialStaticTFsrv request containing the side (in final_set)
  - Create two clients:
    - `asterix/initial_side_selection` (transformix_msgs/InitialStaticTFsrv type),
    - `obelix/initial_side_selection` (transformix_msgs/InitialStaticTFsrv type),
    - Create 2 timers with the exact same behavior than the one described in localisation node above.

## Reminder on the timer:

A timer is asynchronous, to popularize, it acts like a timer interrupt on µC. If it's started, it doesn't block the rest of the program. It will just execute its callback each given time gap.

### CODE REVIEW

**Comment by PhileasL** [comment]
@mAxYoLo01 will strategix and cetautomatix need the side selection too ? If you want, I can do the exact same thing that assurancetourix is doing for localisation but for:
- asterix/cetautomatix,
- asterix/strategix,
- obelix/cetautomatix,
- obelix/strategix,

We just have to discuss about services names.

File: src/assurancetourix/assurancetourix/src/assurancetourix.cpp [hunk 1]
```diff
@@ -45,17 +49,35 @@ Assurancetourix::Assurancetourix() : Node("assurancetourix") {
...
+    RCLCPP_WARN(this->get_logger(), "Assurancetourix detected yellow side");
+    this->declare_parameter<std::string>("side", "yellow");
+    request_initial_tf_asterix_localisation->final_set.data = false;
+    request_initial_tf_obelix_localisation->final_set.data = false;
+  }
   this->get_parameter("side", side);
 
-  set_auto_exposure();
+  timer_side_selection_asterix_localisation = this->create_wall_timer(std::chrono::seconds(2), std::bind(&Assurancetourix::timer_side_service_asterix_callback, this));
+  timer_side_selection_obelix_localisation = this->create_wall_timer(std::chrono::seconds(2), std::bind(&Assurancetourix::timer_side_service_obelix_callback, this));
```
Comment (PhileasL) [inline src/assurancetourix/assurancetourix/src/assurancetourix.cpp:75]: This can be generalized in a struct and a lambda function for sure.

File: src/assurancetourix/assurancetourix/src/assurancetourix.cpp [hunk 2]
```diff
@@ -144,6 +166,49 @@ visualization_msgs::msg::Marker Assurancetourix::predict_enemies_pos(visualizati
...
+        RCLCPP_INFO(this->get_logger(), "obelix initial_tf service acquittal received, end of client operation");
+      } else {
+        RCLCPP_INFO(this->get_logger(), "obelix initial_tf service no acquittal in response, requesting again");
+        spinning_localisation_side_obelix_request = false;
+      }
+    } else {
+      RCLCPP_INFO(this->get_logger(), "obelix initial_tf service not responding, waiting again");
+    }
+  } else RCLCPP_INFO(this->get_logger(), "obelix initial_tf service service not ready");
+}
```
Comment (PhileasL) [inline src/assurancetourix/assurancetourix/src/assurancetourix.cpp:210]: Only one function can be enough for this operation, this will prevent a new service to deserve the same layout and use the generalized one.

Comment (PhileasL) [inline src/assurancetourix/assurancetourix/src/assurancetourix.cpp:210]: Only one function can be enough for this operation, this will prevent a new service to deserve the same layout and use the generalized one.

**Review by PhileasL — COMMENTED** [review]
Generalized service communication through assurancetourix incoming.

**Comment by mAxYoLo01** [comment]
> @mAxYoLo01 will strategix and cetautomatix need the side selection too ? If you want, I can do the exact same thing that assurancetourix is doing for localisation but for:
> 
> * asterix/cetautomatix,
> * asterix/strategix,
> * obelix/cetautomatix,
> * obelix/strategix,
> 
> We just have to discuss about services names.

Actually yes, both nodes need to know the side selected!

**Comment by PhileasL** [comment]
Alright @mAxYoLo01 here's the services you'll have to create in cetautomatix from asterix and obelix and strategix:
- `/asterix/cetautomatix_side_selection`
- `/obelix/cetautomatix_side_selection`
- `/strategix/strategix_side_selection`

Here's the python piece of code in order to create and answer this service: (extracted and adapted from [here](https://github.com/robotique-ecam/cdfr/blob/8084ed330fb70108e4b5de7893e9c7cf3abcf9ba/src/modules/localisation/localisation/localisation_node.py#L95))
``` python
from transformix_msgs.srv import InitialStaticTFsrv

"""in constructor"""
self.side = "blue"
self.side_selection_service = self.create_service(
            InitialStaticTFsrv,
            "<node>_side_selection",
            self.initialSideSelectionCallback,
        ) #node in[cetautomatix, strategix]

"""in class"""
def initialSideSelectionCallback(self, request, response):
        """Assurancetourix send the side of the team"""
        if request.final_set.data:
            self.side = "blue"
        else:
            self.side = "yellow"
        response.acquittal.data = True
        return response
``` 

The fact that the node is already in a namespace prevents us to impose `/asterix/` or `/obelix/`just before the name of the service.

As in the past, the default side is blue !

You can implement it in your future branches or merge master in your current branch and implement it directly.

From now, as soon as side transfer can be done, it'll be done !

**Review by mAxYoLo01 — APPROVED** [review]
LGTM, merging!
And thanks for all the additional information 🍻
